language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
git:
  depth: false
  quiet: true

before_install:
  - npm i -g npm@latest
install:
  - npm ci
script:
  - npm run build